<?php

namespace AbediMostafa\ToDo;

use \Illuminate\Support\ServiceProvider;

class ToDoServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->loadRoutesFrom(__DIR__ . '/routes/api.php');
        $this->loadViewsFrom(__DIR__.'/views', 'todo');
        $this->publishes([
            __DIR__.'/assets' => public_path('vendor/todo'),
        ], 'todo-app');

    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}
